# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
version: 0.2

phases:
  build:
    commands:
      - echo Tests started on `date`
      - echo Running some tests...
