repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.20.0"
    hooks:
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./api-gw-lambda-ecr",
          ]
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./centralized-internet-egress",
          ]
      - id: terraform-docs-go
        args:
          ["markdown", "table", "--output-file", "README.md", "./dns-resolver"]
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./entraid-federation/10_aws_cognito_identity_pool",
          ]
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./entraid-federation/20_entraid",
          ]

      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./ipam-vpc"]

      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./tgw-shared-services/1_tgw",
          ]
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./tgw-shared-services/2_vpcs_acc1",
          ]
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "./tgw-shared-services/3_vpcs_acc2",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
